language: php
dist: trusty

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
    - php: 7.1
      env: SYMFONY_VERSION="2.7.*"
    - php: 7.1
      env: SYMFONY_VERSION="2.8.*@dev symfony/phpunit-bridge:~3.3"
    - php: 7.0
      env: SYMFONY_VERSION="3.*@dev"
  fast_finish: true

before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update --prefer-dist

script:
    - vendor/bin/phpunit
